/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

*/

const PHI = (1 + Math.sqrt(5))/2;
function fibo(num){
    let fibo = 0;
    fibo = Math.round(Math.pow(PHI, num) / Math.sqrt(5);) // http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/Fibonacci/fibFormula.html#calcrsqrt
    return fibo;
}


console.log(fibo(6));